# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Setup Maven
      # You may pin to the exact commit or the version.
      # uses: stCarolas/setup-maven@7060d72b50fbf2389a16d6f66a9c7d4d9ece5d36
      uses: stCarolas/setup-maven@v4.2
      with:
        # Version Spec of the version to use.  Examples: 10.x, 10.15.1, >=10.15.0
        maven-version: 3.8.2
    - run: mvn install
    - name:  Run Tests
      uses: thundra-io/thundra-maven-test-action@v1
      with:
        apikey: 98b7e7a7-5dfc-48d0-871f-c67333b42a9b
        project_id: f5861c97-8575-4435-adad-5d0955e4d52c
        command: mvn test -P single
      env:
          BROWSERSTACK_USERNAME: test18694
          BROWSERSTACK_ACCESS_KEY: zj5FRr2LzdqBi7NXzGQF
